### ISSUE TITLE
Unable to generate a working .prg (under Windows)

### ISSUE THREAD

**Issue by AGPX** [llvm-mos/llvm-mos-sdk#8] opened 2021-10-02 21:48 UTC
Hi,

I'm trying to use the sdk (I've downloaded the binary for the llvm-mos and I've used ninja to compile the sdk) under Windows, but I have the following error:

```
C:\AGPX\Documenti\llvm-mos-sdk>..\llvm-mos\bin\clang.exe -v --config build/commodore/64.cfg -Os -o hello.prg examples/hello_putchar.c
clang version 13.0.0 (https://www.github.com/llvm-mos/llvm-mos.git bb89e37b82ba48e169b47e4fcfd46c4740b4dfeb)
Target: mos
Thread model: posix
InstalledDir: C:\AGPX\Documenti\llvm-mos-sdk\..\llvm-mos\bin
Configuration file: C:\AGPX\Documenti\llvm-mos-sdk\build\commodore\64.cfg
 "C:\\AGPX\\Documenti\\llvm-mos\\bin\\clang.exe" -cc1 -triple mos -emit-llvm-bc -flto -flto-unit -disable-free -disable-llvm-verifier -discard-value-names -main-file-name hello_putchar.c -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -nostdsysteminc -mllvm -force-precise-rotation-cost -mllvm -jump-inst-cost=6 -mllvm -phi-node-folding-threshold=0 -mllvm -two-entry-phi-node-folding-threshold=0 -mllvm -align-large-globals=false -mllvm -disable-spill-hoist -debugger-tuning=gdb -v "-fcoverage-compilation-dir=C:\\AGPX\\Documenti\\llvm-mos-sdk" -resource-dir "C:\\AGPX\\Documenti\\llvm-mos\\lib\\clang\\13.0.0" -isystem C:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/include -isystem C:/AGPX/Documenti/llvm-mos-sdk/build/common/include -internal-isystem "C:\\AGPX\\Documenti\\llvm-mos\\lib\\clang\\13.0.0\\include" -Os "-fdebug-compilation-dir=C:\\AGPX\\Documenti\\llvm-mos-sdk" -ferror-limit 19 -fmessage-length=120 -fno-signed-char -fgnuc-version=4.2.1 -fcolor-diagnostics -vectorize-loops -vectorize-slp -mllvm -num-imag-ptrs=71 -faddrsig -o "C:\\Users\\AGPX\\AppData\\Local\\Temp\\hello_putchar-04578e.o" -x c examples/hello_putchar.c
clang -cc1 version 13.0.0 based upon LLVM 13.0.0git default target x86_64-pc-windows-msvc
ignoring duplicate directory "C:\AGPX\Documenti\llvm-mos\lib\clang\13.0.0\include"
#include "..." search starts here:
#include <...> search starts here:
 C:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/include
 C:/AGPX/Documenti/llvm-mos-sdk/build/common/include
 C:\AGPX\Documenti\llvm-mos\lib\clang\13.0.0\include
End of search list.
 "C:\\AGPX\\Documenti\\llvm-mos-sdk\\..\\llvm-mos\\bin\\ld.lld" -mllvm -num-imag-ptrs=71 --gc-sections "C:\\Users\\AGPX\\AppData\\Local\\Temp\\hello_putchar-04578e.o" -plugin-opt=O2 -mllvm -force-precise-rotation-cost -mllvm -jump-inst-cost=6 -mllvm -phi-node-folding-threshold=0 -mllvm -two-entry-phi-node-folding-threshold=0 -mllvm -align-large-globals=false -mllvm -disable-spill-hoist -LC:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/ldscripts -LC:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/lib -T C:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/ldscripts/link.ld -LC:/AGPX/Documenti/llvm-mos-sdk/build/common/ldscripts -LC:/AGPX/Documenti/llvm-mos-sdk/build/common/lib -l:crt0.o -lcrt -lc -o hello.prg
ld.lld: error: unable to find library -lcrt
ld.lld: error: unable to find library -lc
clang: error: ld.lld command failed with exit code 1 (use -v to see invocation)
```

I discovered that to make it able to found the crt and c library, I have to rename the crt.lib and c.lib (in the 'C:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/lib' directory) to 'libcrt.a' and 'libc.a', but then I have the following error:

```
C:\AGPX\Documenti\llvm-mos-sdk>..\llvm-mos\bin\clang.exe -v --config build/commodore/64.cfg -Os -o hello.prg examples/hello_putchar.c
clang version 13.0.0 (https://www.github.com/llvm-mos/llvm-mos.git bb89e37b82ba48e169b47e4fcfd46c4740b4dfeb)
Target: mos
Thread model: posix
InstalledDir: C:\AGPX\Documenti\llvm-mos-sdk\..\llvm-mos\bin
Configuration file: C:\AGPX\Documenti\llvm-mos-sdk\build\commodore\64.cfg
 "C:\\AGPX\\Documenti\\llvm-mos\\bin\\clang.exe" -cc1 -triple mos -emit-llvm-bc -flto -flto-unit -disable-free -disable-llvm-verifier -discard-value-names -main-file-name hello_putchar.c -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -nostdsysteminc -mllvm -force-precise-rotation-cost -mllvm -jump-inst-cost=6 -mllvm -phi-node-folding-threshold=0 -mllvm -two-entry-phi-node-folding-threshold=0 -mllvm -align-large-globals=false -mllvm -disable-spill-hoist -debugger-tuning=gdb -v "-fcoverage-compilation-dir=C:\\AGPX\\Documenti\\llvm-mos-sdk" -resource-dir "C:\\AGPX\\Documenti\\llvm-mos\\lib\\clang\\13.0.0" -isystem C:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/include -isystem C:/AGPX/Documenti/llvm-mos-sdk/build/common/include -internal-isystem "C:\\AGPX\\Documenti\\llvm-mos\\lib\\clang\\13.0.0\\include" -Os "-fdebug-compilation-dir=C:\\AGPX\\Documenti\\llvm-mos-sdk" -ferror-limit 19 -fmessage-length=120 -fno-signed-char -fgnuc-version=4.2.1 -fcolor-diagnostics -vectorize-loops -vectorize-slp -mllvm -num-imag-ptrs=71 -faddrsig -o "C:\\Users\\AGPX\\AppData\\Local\\Temp\\hello_putchar-614d93.o" -x c examples/hello_putchar.c
clang -cc1 version 13.0.0 based upon LLVM 13.0.0git default target x86_64-pc-windows-msvc
ignoring duplicate directory "C:\AGPX\Documenti\llvm-mos\lib\clang\13.0.0\include"
#include "..." search starts here:
#include <...> search starts here:
 C:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/include
 C:/AGPX/Documenti/llvm-mos-sdk/build/common/include
 C:\AGPX\Documenti\llvm-mos\lib\clang\13.0.0\include
End of search list.
 "C:\\AGPX\\Documenti\\llvm-mos-sdk\\..\\llvm-mos\\bin\\ld.lld" -mllvm -num-imag-ptrs=71 --gc-sections "C:\\Users\\AGPX\\AppData\\Local\\Temp\\hello_putchar-614d93.o" -plugin-opt=O2 -mllvm -force-precise-rotation-cost -mllvm -jump-inst-cost=6 -mllvm -phi-node-folding-threshold=0 -mllvm -two-entry-phi-node-folding-threshold=0 -mllvm -align-large-globals=false -mllvm -disable-spill-hoist -LC:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/ldscripts -LC:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/lib -T C:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/ldscripts/link.ld -LC:/AGPX/Documenti/llvm-mos-sdk/build/common/ldscripts -LC:/AGPX/Documenti/llvm-mos-sdk/build/common/lib -l:crt0.o -lcrt -lc -o hello.prg
ld.lld: error: C:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/lib\libcrt.a(zero_bss.c.obj): unable to find library from dependent library specifier: msvcrtd
ld.lld: error: C:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/lib\libc.a(mem.c.obj): unable to find library from dependent library specifier: msvcrtd
ld.lld: error: C:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/lib\libc.a(chrout.c.obj): unable to find library from dependent library specifier: msvcrtd
ld.lld: error: C:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/lib\libc.a(putchar.c.obj): unable to find library from dependent library specifier: msvcrtd
ld.lld: error: C:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/lib\libcrt.a(shift.cc.obj): unable to find library from dependent library specifier: msvcrtd
ld.lld: error: C:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/lib\libcrt.a(mul.cc.obj): unable to find library from dependent library specifier: msvcrtd
ld.lld: error: C:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/lib\libcrt.a(divmod.cc.obj): unable to find library from dependent library specifier: msvcrtd
clang: error: ld.lld command failed with exit code 1 (use -v to see invocation)
```

what I have to do? Thanks in advance.

**Comment by AGPX** [comment] 2021-10-02 22:24
Ok, I have solved copying the msvcrtd.lib in the 'C:/AGPX/Documenti/llvm-mos-sdk/build/commodore/64/lib' directory and renaming it in 'libmsvcrtd.a', but the hello_putchar.c doesn't works (bad code generation, looks like it output a 'brk').

**Comment by Galfodo** [comment] 2021-12-07 16:09
I had the same problems. Here's what I did to fix it for myself:

https://github.com/llvm-mos/llvm-mos-sdk/compare/main...Galfodo:windows-buildsystem-fixes?expand=1

**Comment by mysterymath** [comment] 2021-12-07 16:37
Just a heads up, @jackoalan is working on a more principled solution for Windows support in the SDK.

The root of the problem is that CMake defaults the target platform to the host platform (Windows), even when cross compiling. This doesn't cause any problems on Linux, but it does on Windows.

Should be a PR landing relatively soon with a CMake toolchain file that configures the MOS compilation environment with sensible defaults.

**Comment by Galfodo** [comment] 2021-12-07 17:09
Nice :) I was going to elaborate on my local changes, but I guess there will be no need. Having host and cross compilation targets in the same (cmake) project is probably not a good idea.

**Comment by jackoalan** [comment] 2022-01-09 16:52
The SDK refactor is finally merged and tested to work with a Visual Studio 2019 host toolchain. Follow the steps in the updated README (particularly the note for Windows users).

If using CMake for your application project, you may now use `find_project(llvm-mos-sdk REQUIRED)` as described in the README. Alternatively, existing CMake projects can use the toolchain file via `-DCMAKE_TOOLCHAIN_FILE=<sdk-install-prefix>/lib/cmake/llvm-mos-sdk/llvm-mos-toolchain.cmake -DLLVM_MOS_PLATFORM=<platform>`. This will ensure that Windows-specific compiler flags do not interfere.

**Closed by jackoalan** 2022-01-09 16:52 UTC
